#!/opt/bin/sh
# Show nginx-webui diagnostic status.
# shellcheck disable=SC3043  # 'local' supported by ash/busybox sh
# shellcheck disable=SC1091
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/../config/defaults.conf"
[ -f "$SCRIPT_DIR/../config/config.conf" ] && . "$SCRIPT_DIR/../config/config.conf"
. "$SCRIPT_DIR/../../lib/common.sh"
. "$SCRIPT_DIR/../../lib/status.sh"

CONF="$SCRIPT_DIR/../config/nginx.conf"
LISTEN_CONF="$SCRIPT_DIR/../config/listen.conf"
BASE_URL="http://127.0.0.1:${LISTEN_PORT}"

STATUS_OK=0

# Pre-init globals set by lib/status.sh functions
_st_pid="" _st_pid_source=""
_st_running="false" _st_mem_kb="0"
_st_uptime_seconds=0
_st_port_ok="false" _st_port_addrs=""
_st_version=""
_ck_upstream_ok=1
_ck_upstream_addr=""
_ck_upstream_code=""

# --- Check functions (specific to webui) ---

# Check nginx config file presence.
# Sets: _ck_config_ok ("true"|"false")
check_config() {
  if [ -f "$CONF" ]; then
    _ck_config_ok="true"
  else
    _ck_config_ok="false"
  fi
}

# Check listen.conf presence (generated by postinst).
# Sets: _ck_listen_conf_ok ("true"|"false")
check_listen_conf() {
  if [ -f "$LISTEN_CONF" ]; then
    _ck_listen_conf_ok="true"
  else
    _ck_listen_conf_ok="false"
  fi
}

# Check Lua dynamic module presence.
# Sets: _ck_lua_module_ok ("true"|"false")
check_lua_module() {
  if [ -f "/opt/lib/nginx/modules/ngx_http_lua_module.so" ]; then
    _ck_lua_module_ok="true"
  else
    _ck_lua_module_ok="false"
  fi
}

# Check logrotate setup (binary + config + cron daily).
# Sets: _ck_logrotate_ok ("true"|"false")
check_logrotate() {
  if [ -x "/opt/sbin/logrotate" ] \
     && [ -f "/opt/etc/logrotate.d/nginx-webui" ] \
     && [ -x "/opt/etc/cron.daily/logrotate" ]; then
    _ck_logrotate_ok="true"
  else
    _ck_logrotate_ok="false"
  fi
}

# Check stock Keenetic httpd (upstream) reachability.
# Parses listen.conf for $stock_httpd variable, then checks TCP port.
# Uses netstat (instant) instead of curl (up to 3s blocking) to avoid
# stalling the nginx worker queue when called via io.popen in --json mode.
# Sets: _ck_upstream_ok (0=reachable, 1=unreachable), _ck_upstream_addr
check_upstream() {
  _ck_upstream_ok=1
  _ck_upstream_addr=""
  _ck_upstream_code=""

  # Extract upstream address from listen.conf (format: set $stock_httpd http://IP:PORT;)
  if [ -f "$LISTEN_CONF" ]; then
    _ck_upstream_addr=$(sed -n 's|.*stock_httpd *http://\([^;]*\);|\1|p' "$LISTEN_CONF")
  fi
  [ -z "$_ck_upstream_addr" ] && _ck_upstream_addr="127.0.0.1:80"

  # Check TCP port listening via netstat (instant, no network I/O)
  local up_port
  up_port="${_ck_upstream_addr##*:}"
  if netstat -tln 2>/dev/null | grep -q ":${up_port} "; then
    _ck_upstream_ok=0
    _ck_upstream_code="listening"
  fi
}

# Check firmware patch state.
# Reads /tmp/ew-webui/.patch-state written by patch-stock-ui.sh.
# Sets: _ck_patch_set ("v1"|"v2"|"v3"|""), _ck_fw_version, _ck_patch_ok ("true"|"false")
check_patch_compat() {
  _ck_patch_set=""
  _ck_fw_version=""
  _ck_patch_ok="false"
  local _state="/tmp/ew-webui/.patch-state"
  if [ -f "$_state" ]; then
    # State file is key=value (PATCH_SET, FW_VERSION, JS_HASH, CSS_HASH)
    # shellcheck source=/dev/null
    . "$_state"
    _ck_patch_set="${PATCH_SET:-}"
    _ck_fw_version="${FW_VERSION:-}"
    [ -n "$_ck_patch_set" ] && _ck_patch_ok="true"
  else
    # Fallback: get firmware version from ndmc (state file missing = not patched)
    if command -v ndmc >/dev/null 2>&1; then
      _ck_fw_version=$(ndmc -c "show version" 2>/dev/null | awk '/title:/ { print $2; exit }')
    fi
  fi
}

# --- Show functions (text, specific to webui) ---

# Show config file presence.
show_config() {
  if [ "$_ck_config_ok" = "true" ]; then
    status_line "Config" "$CONF" "ok"
  else
    status_line "Config" "$CONF NOT FOUND" "fail"
  fi
}

# Show listen.conf presence.
show_listen_conf() {
  if [ "$_ck_listen_conf_ok" = "true" ]; then
    status_line "Listen conf" "$LISTEN_CONF" "ok"
  else
    status_line "Listen conf" "$LISTEN_CONF NOT FOUND" "fail"
  fi
}

# Show Lua dynamic module presence.
show_lua_module() {
  local mod="/opt/lib/nginx/modules/ngx_http_lua_module.so"
  if [ "$_ck_lua_module_ok" = "true" ]; then
    status_line "Lua module" "$mod" "ok"
  else
    status_line "Lua module" "$mod NOT FOUND" "fail"
  fi
}

# Show logrotate status (3 sub-checks with details).
show_logrotate() {
  if [ -x "/opt/sbin/logrotate" ]; then
    status_line "Binary" "/opt/sbin/logrotate" "ok"
  else
    status_line "Binary" "/opt/sbin/logrotate NOT FOUND" "fail"
  fi

  if [ -f "/opt/etc/logrotate.d/nginx-webui" ]; then
    status_line "Config" "/opt/etc/logrotate.d/nginx-webui" "ok"
  else
    status_line "Config" "/opt/etc/logrotate.d/nginx-webui NOT FOUND" "fail"
  fi

  if [ -x "/opt/etc/cron.daily/logrotate" ]; then
    status_line "Cron daily" "/opt/etc/cron.daily/logrotate" "ok"
  else
    status_line "Cron daily" "/opt/etc/cron.daily/logrotate NOT FOUND" "fail"
  fi
}

# Show upstream (stock httpd) reachability.
show_upstream() {
  if [ "$_ck_upstream_ok" = 0 ]; then
    status_line "Stock httpd" "${_ck_upstream_addr} → ${_ck_upstream_code}" "ok"
  else
    status_line "Stock httpd" "${_ck_upstream_addr} → ${_ck_upstream_code:-timeout}" "fail"
  fi
}

# Show HTTP endpoint checks (static page + API).
show_http() {
  if ! command -v curl >/dev/null 2>&1; then
    status_line "HTTP" "curl not available, skipping"
    return
  fi

  local http_code
  http_code="$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 3 --max-time 5 "${BASE_URL}/" 2>/dev/null)" || true
  if [ "$http_code" = "200" ]; then
    status_line "Static" "GET / → $http_code" "ok"
  else
    status_line "Static" "GET / → ${http_code:-timeout}" "fail"; STATUS_OK=1
  fi

  http_code="$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 3 --max-time 5 "${BASE_URL}/api/system/info" 2>/dev/null)" || true
  if [ "$http_code" = "200" ]; then
    status_line "API" "GET /api/system/info → $http_code" "ok"
  else
    status_line "API" "GET /api/system/info → ${http_code:-timeout}" "fail"; STATUS_OK=1
  fi
}

# Show patch compatibility info.
show_patch_compat() {
  if [ -z "$_ck_fw_version" ]; then
    status_line "Firmware" "unknown (ndmc unavailable)"
  elif [ "$_ck_patch_ok" = "true" ]; then
    status_line "Firmware" "$_ck_fw_version → patch ${_ck_patch_set}" "ok"
  else
    status_line "Firmware" "$_ck_fw_version → no patch set" "warn"
  fi
}

# --- JSON output ---

# Collect structured data and emit JSON for webui.
json_output() {
  local config_ok_val=1 lua_module_ok_val=1 http_ok_val=1 logrotate_ok_val=1
  local upstream_ok_val="$_ck_upstream_ok"
  local mem_formatted=""

  [ "$_ck_config_ok" = "true" ] && config_ok_val=0 || true
  [ "$_ck_lua_module_ok" = "true" ] && lua_module_ok_val=0 || true
  [ "$_ck_logrotate_ok" = "true" ] && logrotate_ok_val=0 || true

  # HTTP ok: use port_listening as proxy (avoids curl recursion via nginx lua)
  [ "$_st_port_ok" = "true" ] && http_ok_val=0 || true

  # Format memory
  if [ "$_st_mem_kb" != "0" ] && [ -n "$_st_mem_kb" ]; then
    mem_formatted="$(format_size_kb "$_st_mem_kb")"
  fi

  # Ports display: use detected addrs or fall back to port number
  local ports_val="$_st_port_addrs"
  [ -z "$ports_val" ] && ports_val="$LISTEN_PORT" || true

  # Enabled: symlink exists in /opt/etc/init.d/
  local enabled_val=1
  is_service_enabled "S80nginx-webui" && enabled_val=0

  # Details — Service status
  status_detail "ports" "$ports_val"
  status_detail "status" "$([ "$_st_port_ok" = "true" ] && echo 0 || echo 1)" "bool"
  status_detail "config" "$config_ok_val" "bool"
  status_detail "firmware" "${_ck_fw_version:-unknown}"
  status_detail "patch_set" "${_ck_patch_set:-none}"
  # Details — Infrastructure
  status_detail "upstream" "$_ck_upstream_addr"
  status_detail "lua_module" "$lua_module_ok_val" "bool"
  status_detail "http" "$http_ok_val" "bool"
  # Details — Resources
  status_detail "pid" "$_st_pid"
  status_detail "memory" "$mem_formatted"
  status_detail "logrotate" "$logrotate_ok_val" "bool"
  status_detail "cache" "0" "bool"
  # Details — System
  status_detail "uptime" "$_st_uptime_seconds" "num"
  status_detail "version" "${_st_version:-unknown}"

  # Checks
  status_check_result "process" "$(if [ "$_st_running" = "true" ]; then printf ok; else printf fail; fi)"
  status_check_result "config" "$(if [ "$config_ok_val" = 0 ]; then printf ok; else printf fail; fi)"
  status_check_result "lua_module" "$(if [ "$lua_module_ok_val" = 0 ]; then printf ok; else printf fail; fi)"
  status_check_result "http" "$(if [ "$http_ok_val" = 0 ]; then printf ok; else printf fail; fi)"
  status_check_result "logrotate" "$(if [ "$logrotate_ok_val" = 0 ]; then printf ok; else printf warn; fi)"
  status_check_result "upstream" "$(if [ "$upstream_ok_val" = 0 ]; then printf ok; else printf warn; fi)"
  status_check_result "patch_set" "$(if [ "$_ck_patch_ok" = "true" ]; then printf ok; elif [ -z "$_ck_fw_version" ]; then printf ok; else printf warn; fi)"

  # Emit
  status_emit_json "$enabled_val" "$([ "$_st_running" = "true" ] && echo 0 || echo 1)" "$STATUS_OK"
}


# --- main ---

# Run all checks upfront
status_detect_pid "$PIDFILE" "nginx"
status_check_process
status_check_uptime "$PIDFILE"
status_check_port "$LISTEN_PORT" "tcp"
status_check_version "webui"
check_config
check_listen_conf
check_lua_module
check_logrotate
check_upstream
check_patch_compat

# Determine STATUS_OK
[ "$_st_running" = "false" ] && STATUS_OK=1
[ "$_st_port_ok" = "false" ] && STATUS_OK=1
[ "$_ck_config_ok" = "false" ] && STATUS_OK=1
[ "$_ck_listen_conf_ok" = "false" ] && STATUS_OK=1
[ "$_ck_lua_module_ok" = "false" ] && STATUS_OK=1
[ "$_ck_logrotate_ok" = "false" ] && STATUS_OK=1
# Note: upstream_ok is not fatal — stock httpd could be temporarily down
# but webui still serves custom dashboard. Reported as "warn" in checks.

# --- Text output (declarative, parallel to json_output) ---

text_output() {
  # Determine status word for title line
  local _status_word="✓ Alive"
  if ! is_service_enabled "S80nginx-webui"; then
    _status_word="⚠ Disabled"
  elif [ "$STATUS_OK" -ne 0 ]; then
    _status_word="✗ Fail"
  fi

  _text_buf="nginx-webui status: ${_status_word}
"
  status_section "Service"
  status_show_process
  show_config
  show_listen_conf
  show_lua_module
  status_show_port "$LISTEN_PORT"
  status_blank
  status_section "HTTP"
  show_http
  status_blank
  status_section "Upstream"
  show_upstream
  status_blank
  status_section "Logrotate"
  show_logrotate
  status_blank
  status_section "Patch"
  show_patch_compat
  status_blank
  status_section "System"
  status_show_uptime
  status_show_version

  status_emit_text
}

# --- main ---

if [ "${1:-}" = "--json" ]; then
  json_output
  exit "$STATUS_OK"
fi

text_output
exit "$STATUS_OK"
