#!/opt/bin/sh
# Show nginx-webui diagnostic status.
# shellcheck disable=SC3043  # 'local' supported by ash/busybox sh
# shellcheck disable=SC1091
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
. "$SCRIPT_DIR/../config/defaults.conf"
[ -f "$SCRIPT_DIR/../config/config.conf" ] && . "$SCRIPT_DIR/../config/config.conf"
. "$SCRIPT_DIR/../../lib/common.sh"
. "$SCRIPT_DIR/../../lib/status.sh"

CONF="$SCRIPT_DIR/../config/nginx.conf"
LISTEN_CONF="$SCRIPT_DIR/../config/listen.conf"
BASE_URL="http://127.0.0.1:${LISTEN_PORT}"

STATUS_OK=0

# Pre-init globals set by lib/status.sh functions
_st_pid="" _st_pid_source=""
_st_running="false" _st_mem_kb="0"
_st_uptime_seconds=0
_st_port_ok="false" _st_port_addrs=""
_st_version=""

# --- Check functions (specific to webui) ---

# Check nginx config file presence.
# Sets: _ck_config_ok ("true"|"false")
check_config() {
  if [ -f "$CONF" ]; then
    _ck_config_ok="true"
  else
    _ck_config_ok="false"
  fi
}

# Check listen.conf presence (generated by postinst).
# Sets: _ck_listen_conf_ok ("true"|"false")
check_listen_conf() {
  if [ -f "$LISTEN_CONF" ]; then
    _ck_listen_conf_ok="true"
  else
    _ck_listen_conf_ok="false"
  fi
}

# Check Lua dynamic module presence.
# Sets: _ck_lua_module_ok ("true"|"false")
check_lua_module() {
  if [ -f "/opt/lib/nginx/modules/ngx_http_lua_module.so" ]; then
    _ck_lua_module_ok="true"
  else
    _ck_lua_module_ok="false"
  fi
}

# Check logrotate setup (binary + config + cron daily).
# Sets: _ck_logrotate_ok ("true"|"false")
check_logrotate() {
  if [ -x "/opt/sbin/logrotate" ] \
     && [ -f "/opt/etc/logrotate.d/nginx-webui" ] \
     && [ -x "/opt/etc/cron.daily/logrotate" ]; then
    _ck_logrotate_ok="true"
  else
    _ck_logrotate_ok="false"
  fi
}

# --- Show functions (text, specific to webui) ---

# Show config file presence.
show_config() {
  if [ "$_ck_config_ok" = "true" ]; then
    echo "    Config:      $CONF ✓"
  else
    echo "    Config:      $CONF NOT FOUND ✗"
  fi
}

# Show listen.conf presence.
show_listen_conf() {
  if [ "$_ck_listen_conf_ok" = "true" ]; then
    echo "    Listen conf: $LISTEN_CONF ✓"
  else
    echo "    Listen conf: $LISTEN_CONF NOT FOUND ✗"
  fi
}

# Show Lua dynamic module presence.
show_lua_module() {
  local mod="/opt/lib/nginx/modules/ngx_http_lua_module.so"
  if [ "$_ck_lua_module_ok" = "true" ]; then
    echo "    Lua module:  $mod ✓"
  else
    echo "    Lua module:  $mod NOT FOUND ✗"
  fi
}

# Show logrotate status (3 sub-checks with details).
show_logrotate() {
  if [ -x "/opt/sbin/logrotate" ]; then
    echo "    Binary:      /opt/sbin/logrotate ✓"
  else
    echo "    Binary:      /opt/sbin/logrotate NOT FOUND ✗"
  fi

  if [ -f "/opt/etc/logrotate.d/nginx-webui" ]; then
    echo "    Config:      /opt/etc/logrotate.d/nginx-webui ✓"
  else
    echo "    Config:      /opt/etc/logrotate.d/nginx-webui NOT FOUND ✗"
  fi

  if [ -x "/opt/etc/cron.daily/logrotate" ]; then
    echo "    Cron daily:  /opt/etc/cron.daily/logrotate ✓"
  else
    echo "    Cron daily:  /opt/etc/cron.daily/logrotate NOT FOUND ✗"
  fi
}

# Show HTTP endpoint checks (static page + API).
show_http() {
  if ! command -v curl >/dev/null 2>&1; then
    echo "    HTTP:        curl not available, skipping"
    return
  fi

  local http_code
  http_code="$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 3 --max-time 5 "${BASE_URL}/" 2>/dev/null)" || true
  if [ "$http_code" = "200" ]; then
    echo "    Static:      GET / → $http_code ✓"
  else
    echo "    Static:      GET / → ${http_code:-timeout} ✗"; STATUS_OK=1
  fi

  http_code="$(curl -s -o /dev/null -w '%{http_code}' --connect-timeout 3 --max-time 5 "${BASE_URL}/api/system/info" 2>/dev/null)" || true
  if [ "$http_code" = "200" ]; then
    echo "    API:         GET /api/system/info → $http_code ✓"
  else
    echo "    API:         GET /api/system/info → ${http_code:-timeout} ✗"; STATUS_OK=1
  fi
}

# --- JSON output ---

# Collect structured data and emit JSON for webui.
json_output() {
  local config_ok_val=1 lua_module_ok_val=1 http_ok_val=1 logrotate_ok_val=1
  local mem_formatted=""

  [ "$_ck_config_ok" = "true" ] && config_ok_val=0 || true
  [ "$_ck_lua_module_ok" = "true" ] && lua_module_ok_val=0 || true
  [ "$_ck_logrotate_ok" = "true" ] && logrotate_ok_val=0 || true

  # HTTP ok: use port_listening as proxy (avoids curl recursion via nginx lua)
  [ "$_st_port_ok" = "true" ] && http_ok_val=0 || true

  # Format memory
  if [ "$_st_mem_kb" != "0" ] && [ -n "$_st_mem_kb" ]; then
    mem_formatted="$(format_size_kb "$_st_mem_kb")"
  fi

  # Ports display: use detected addrs or fall back to port number
  local ports_val="$_st_port_addrs"
  [ -z "$ports_val" ] && ports_val="$LISTEN_PORT" || true

  printf '{'
  json_kv_bool "running" "$([ "$_st_running" = "true" ] && echo 0 || echo 1)"
  printf ','
  json_kv_bool "ok" "$STATUS_OK"
  printf ',"details":{'
  json_kv "ports" "$ports_val"
  printf ','
  json_kv_bool "status" "$([ "$_st_port_ok" = "true" ] && echo 0 || echo 1)"
  printf ','
  json_kv_bool "config" "$config_ok_val"
  printf ','
  json_kv_bool "lua_module" "$lua_module_ok_val"
  printf ','
  json_kv_bool "http" "$http_ok_val"
  printf ','
  json_kv "pid" "$_st_pid"
  printf ','
  json_kv "memory" "$mem_formatted"
  printf ','
  json_kv_bool "logrotate" "$logrotate_ok_val"
  printf ','
  json_kv_num "uptime" "$_st_uptime_seconds"
  printf ','
  json_kv "version" "${_st_version:-unknown}"
  printf '},'

  # Checks section: "ok"|"warn"|"fail" per field
  printf '"checks":{'
  json_check "process" "$(if [ "$_st_running" = "true" ]; then printf ok; else printf fail; fi)"
  printf ','
  json_check "config" "$(if [ "$config_ok_val" = 0 ]; then printf ok; else printf fail; fi)"
  printf ','
  json_check "lua_module" "$(if [ "$lua_module_ok_val" = 0 ]; then printf ok; else printf fail; fi)"
  printf ','
  json_check "http" "$(if [ "$http_ok_val" = 0 ]; then printf ok; else printf fail; fi)"
  printf ','
  json_check "logrotate" "$(if [ "$logrotate_ok_val" = 0 ]; then printf ok; else printf warn; fi)"
  printf '}}\n'
}

# --- main ---

# Run all checks upfront
status_detect_pid "$PIDFILE" "nginx"
status_check_process
status_check_uptime "$PIDFILE"
status_check_port "$LISTEN_PORT" "tcp"
status_check_version "webui"
check_config
check_listen_conf
check_lua_module
check_logrotate

# Determine STATUS_OK
[ "$_st_running" = "false" ] && STATUS_OK=1
[ "$_st_port_ok" = "false" ] && STATUS_OK=1
[ "$_ck_config_ok" = "false" ] && STATUS_OK=1
[ "$_ck_listen_conf_ok" = "false" ] && STATUS_OK=1
[ "$_ck_lua_module_ok" = "false" ] && STATUS_OK=1
[ "$_ck_logrotate_ok" = "false" ] && STATUS_OK=1

if [ "${1:-}" = "--json" ]; then
  json_output
  exit "$STATUS_OK"
fi

echo "nginx-webui status:"
echo "  Service:"
status_show_process
show_config
show_listen_conf
show_lua_module
status_show_port "$LISTEN_PORT"
echo
echo "  HTTP:"
show_http
echo
echo "  Logrotate:"
show_logrotate
echo
echo "  System:"
status_show_uptime
status_show_version

exit "$STATUS_OK"
