#!/opt/bin/sh
# Generate SmartDNS config snippets from config.conf settings.
# Produces:
#   dns-servers-other.conf — international DNS (default group, with -interface if set)
#   dns-zones-active.conf  — meta-include referencing active zone presets
#
# Zone presets are static files in config/zones/<cc>.conf.
# This script only generates the "other" servers (needs -interface handling)
# and the active-zones meta-include.
#
# Called by: postinst, toggle.sh enable
# shellcheck disable=SC3043  # 'local' supported by ash/busybox sh
# shellcheck disable=SC1091  # sourced files resolved at runtime on router
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
_CONFIG_DIR="${SCRIPT_DIR%/*}/config"
. "$_CONFIG_DIR/defaults.conf"
[ -f "$_CONFIG_DIR/config.conf" ] && . "$_CONFIG_DIR/config.conf"
. "$SCRIPT_DIR/../../lib/geo.sh"

# Base path where zone preset files live
ZONES_DIR="$_CONFIG_DIR/zones"


# ===================================================================
# Generate: international (other) DNS servers — default group
# ===================================================================
generate_other_servers() {
  local out="$CONF_SERVERS_OTHER"

  cat > "$out" <<'HEADER'
# Auto-generated by smartdns-geo-conf/scripts/generate-conf.sh
# International DNS servers (default group).
# Do not edit — regenerated on config change.

HEADER

  if [ -n "$OTHER_DNS_INTERFACES" ]; then
    # VPN-bound servers (one Google + one Cloudflare per interface)
    local idx=0
    for iface in $OTHER_DNS_INTERFACES; do
      # Skip "default" pseudo-value (means default route — servers without -interface)
      [ "$iface" = "default" ] && continue
      local iface_flag="-interface $iface"
      if [ $((idx % 2)) -eq 0 ]; then
        cat >> "$out" <<EOF
# Google DoH via $iface
server-https https://dns.google/dns-query \\
    -host-name dns.google \\
    -http-host dns.google \\
    -host-ip 8.8.8.8 \\
    -tls-host-verify dns.google \\
    $iface_flag

# Cloudflare DoH via $iface
server-https https://cloudflare-dns.com/dns-query \\
    -host-name cloudflare-dns.com \\
    -http-host cloudflare-dns.com \\
    -host-ip 1.1.1.1 \\
    -tls-host-verify cloudflare-dns.com \\
    $iface_flag

EOF
      else
        cat >> "$out" <<EOF
# Google DoH via $iface
server-https https://dns.google/dns-query \\
    -host-name dns.google \\
    -http-host dns.google \\
    -host-ip 8.8.4.4 \\
    -tls-host-verify dns.google \\
    $iface_flag

# Cloudflare DoH via $iface
server-https https://cloudflare-dns.com/dns-query \\
    -host-name cloudflare-dns.com \\
    -http-host cloudflare-dns.com \\
    -host-ip 1.0.0.1 \\
    -tls-host-verify cloudflare-dns.com \\
    $iface_flag

EOF
      fi
      idx=$((idx + 1))
    done

    # Fallback without VPN (direct)
    cat >> "$out" <<'EOF'
# Fallback — direct (no VPN), used if all VPN interfaces are down
server-https https://dns.google/dns-query \
    -host-name dns.google \
    -http-host dns.google \
    -host-ip 8.8.8.8 \
    -tls-host-verify dns.google

server-https https://cloudflare-dns.com/dns-query \
    -host-name cloudflare-dns.com \
    -http-host cloudflare-dns.com \
    -host-ip 1.1.1.1 \
    -tls-host-verify cloudflare-dns.com
EOF
  else
    # No VPN — direct only
    cat >> "$out" <<'EOF'
# Google DoH (direct)
server-https https://dns.google/dns-query \
    -host-name dns.google \
    -http-host dns.google \
    -host-ip 8.8.8.8 \
    -tls-host-verify dns.google

server-https https://dns.google/dns-query \
    -host-name dns.google \
    -http-host dns.google \
    -host-ip 8.8.4.4 \
    -tls-host-verify dns.google

# Cloudflare DoH (direct)
server-https https://cloudflare-dns.com/dns-query \
    -host-name cloudflare-dns.com \
    -http-host cloudflare-dns.com \
    -host-ip 1.1.1.1 \
    -tls-host-verify cloudflare-dns.com

server-https https://cloudflare-dns.com/dns-query \
    -host-name cloudflare-dns.com \
    -http-host cloudflare-dns.com \
    -host-ip 1.0.0.1 \
    -tls-host-verify cloudflare-dns.com
EOF
  fi
}

# ===================================================================
# Generate: dns-zones-active.conf (meta-include for active zone presets)
# ===================================================================
generate_zones_active() {
  local out="${SMARTDNS_CONF_DIR}/dns-zones-active.conf"
  local zones
  zones="$(resolve_geo_zone "$DNS_ZONE")"
  local active_count=0
  local skipped=""

  cat > "$out" <<EOF
# Auto-generated by smartdns-geo-conf/scripts/generate-conf.sh
# DNS_ZONE=$DNS_ZONE → zones: $zones
EOF

  for cc in $zones; do
    local zone_preset="${ZONES_DIR}/${cc}.conf"
    if [ -f "$zone_preset" ]; then
      printf 'conf-file %s\n' "$zone_preset" >> "$out"
      active_count=$((active_count + 1))
    else
      skipped="${skipped} ${cc}"
    fi
  done

  if [ -n "$skipped" ]; then
    echo "generate-conf: WARNING: no zone preset for:${skipped} (create config/zones/<cc>.conf)" >&2
  fi

  echo "generate-conf: DNS_ZONE=$DNS_ZONE, activated $active_count zone(s): $zones"
}

# ===================================================================
# Main
# ===================================================================
main() {
  mkdir -p "$SMARTDNS_CONF_DIR"

  # Generate international DNS servers config
  generate_other_servers
  echo "generate-conf: OTHER_DNS_INTERFACES=${OTHER_DNS_INTERFACES:-(direct)}"

  # Generate meta-include for active zones
  generate_zones_active

  if [ -n "$ZONE_DNS_INTERFACE" ] && [ "$ZONE_DNS_INTERFACE" != "default" ]; then
    echo "generate-conf: ZONE_DNS_INTERFACE=$ZONE_DNS_INTERFACE"
    echo "generate-conf: NOTE: -interface for zone DNS requires manual edit of zone presets"
  fi
}

main
