#!/opt/bin/sh
# Generate SmartDNS config snippets from dns-providers.conf + zone-routing-rules.conf.
# Produces:
#   dns-servers-other.conf  — international DNS (default group, with -interface if set)
#   dns-zones-active.conf   — zone upstream servers + nameserver routing rules (all-in-one)
#
# Dynamic generation: no static zone files needed. Reads provider catalog
# and routing rules to build everything at runtime.
#
# Called by: postinst, toggle.sh enable
# shellcheck disable=SC3043  # 'local' supported by ash/busybox sh
# shellcheck disable=SC1091  # sourced files resolved at runtime on router
set -eu

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
_CONFIG_DIR="${SCRIPT_DIR%/*}/config"
. "$_CONFIG_DIR/defaults.conf"
[ -f "$_CONFIG_DIR/config.conf" ] && . "$_CONFIG_DIR/config.conf"
. "$_CONFIG_DIR/dns-providers.conf"
. "$SCRIPT_DIR/../../lib/geo.sh"

# Zone routing rules file
ROUTING_RULES="$_CONFIG_DIR/zone-routing-rules.conf"

# ===================================================================
# Helpers: dynamic provider variable lookup (POSIX sh)
# ===================================================================

# Get OTHER provider variable value.
# Usage: get_other_prov <provider> <field>
# Example: get_other_prov google IP1 → "8.8.8.8"
get_other_prov() {
  eval "printf '%s' \"\$OTHER_${1}_${2}\""
}

# Get ZONE provider variable value.
# Usage: get_zone_prov <provider> <field>
# Example: get_zone_prov yandex TLS_HOST → "common.dot.dns.yandex.net"
get_zone_prov() {
  eval "printf '%s' \"\$ZONE_${1}_${2}\""
}

# Resolve ISP DNS IPs dynamically from /tmp/ndnproxymain.conf (Keenetic).
# Filters: SmartDNS forwarding (:6053), loopback (127.*).
# Returns up to 2 IPs, one per line.
_get_isp_dns_ips() {
  local _ips=""
  if [ -f /tmp/ndnproxymain.conf ]; then
    # Format: "dns_server = <IP>[:port] ." — field 3 is IP:port
    _ips="$(grep '^dns_server' /tmp/ndnproxymain.conf | awk '{print $3}' | grep -v ':6053' | sed 's/:.*//' | grep -v '^127\.' | head -2)"
  fi
  printf '%s' "$_ips"
}

# ===================================================================
# Generate: international (other) DNS servers — default group
# ===================================================================
generate_other_servers() {
  local out="$CONF_SERVERS_OTHER"

  cat > "$out" <<'HEADER'
# Auto-generated by smartdns-geo-conf/scripts/generate-conf.sh
# International DNS servers (default group).
# Do not edit — regenerated on config change.

HEADER

  for provider in $OTHER_DNS_PROVIDER; do
    local proto
    proto="$(get_other_prov "$provider" PROTO)"

    # UDP protocol (ISP Default) — no IP/TLS fields, handle early
    if [ "$proto" = "udp" ]; then
      local _resolv_ips
      _resolv_ips="$(_get_isp_dns_ips)"
      if [ -n "$_resolv_ips" ]; then
        printf '# %s — ISP Default (plain UDP)\n' "$provider" >> "$out"
        for _rip in $_resolv_ips; do
          printf 'server %s\n' "$_rip" >> "$out"
        done
        printf '\n' >> "$out"
      else
        printf '# %s — ISP Default: no ISP DNS found in ndnproxymain.conf\n\n' "$provider" >> "$out"
      fi
      continue
    fi

    local ip1 ip2 tls_host doh_url
    ip1="$(get_other_prov "$provider" IP1)"
    ip2="$(get_other_prov "$provider" IP2)"
    tls_host="$(get_other_prov "$provider" TLS_HOST)"
    doh_url="$(get_other_prov "$provider" DOH_URL)" 2>/dev/null || doh_url=""

    # Determine interface flags
    local iface_list=""
    if [ -n "$OTHER_DNS_INTERFACES" ]; then
      iface_list="$OTHER_DNS_INTERFACES"
    fi

    case "$proto" in
      doh)
        # With VPN interfaces
        if [ -n "$iface_list" ]; then
          for iface in $iface_list; do
            [ "$iface" = "default" ] && continue
            _emit_doh_server "$out" "$provider" "$doh_url" "$ip1" "$tls_host" "-interface $iface"
            if [ -n "$ip2" ]; then
              _emit_doh_server "$out" "$provider" "$doh_url" "$ip2" "$tls_host" "-interface $iface"
            fi
          done
        fi
        # Fallback / direct (always present)
        _emit_doh_server "$out" "$provider" "$doh_url" "$ip1" "$tls_host" ""
        if [ -n "$ip2" ]; then
          _emit_doh_server "$out" "$provider" "$doh_url" "$ip2" "$tls_host" ""
        fi
        ;;
      dot)
        # With VPN interfaces
        if [ -n "$iface_list" ]; then
          for iface in $iface_list; do
            [ "$iface" = "default" ] && continue
            _emit_dot_server "$out" "$provider" "$ip1" "$tls_host" "" "-interface $iface"
            if [ -n "$ip2" ]; then
              _emit_dot_server "$out" "$provider" "$ip2" "$tls_host" "" "-interface $iface"
            fi
          done
        fi
        # Fallback / direct
        _emit_dot_server "$out" "$provider" "$ip1" "$tls_host" "" ""
        if [ -n "$ip2" ]; then
          _emit_dot_server "$out" "$provider" "$ip2" "$tls_host" "" ""
        fi
        ;;
    esac
  done
}

# Emit a single DoH server entry.
# Args: $1=file $2=label $3=doh_url $4=ip $5=tls_host $6=extra_flags
_emit_doh_server() {
  local _file="$1" _label="$2" _url="$3" _ip="$4" _host="$5" _flags="$6"
  local _suffix=""
  [ -n "$_flags" ] && _suffix=" \\
    $_flags"
  cat >> "$_file" <<EOF
# ${_label} DoH${_flags:+ (${_flags#-interface })}
server-https ${_url} \\
    -host-name ${_host} \\
    -http-host ${_host} \\
    -host-ip ${_ip} \\
    -tls-host-verify ${_host}${_suffix}

EOF
}

# Emit a single DoT server entry.
# Args: $1=file $2=label $3=ip $4=tls_host $5=group_flags $6=extra_flags
_emit_dot_server() {
  local _file="$1" _label="$2" _ip="$3" _host="$4" _group="$5" _flags="$6"
  local _suffix=""
  [ -n "$_group" ] && _suffix=" ${_group}"
  [ -n "$_flags" ] && _suffix="${_suffix} \\
    ${_flags}"
  cat >> "$_file" <<EOF
server-tls ${_ip}:853${_suffix} \\
    -host-name ${_host} \\
    -tls-host-verify ${_host}

EOF
}

# ===================================================================
# Generate: dns-zones-active.conf (zone servers + nameserver routing)
# ===================================================================
generate_zones_active() {
  local out="${SMARTDNS_CONF_DIR}/dns-zones-active.conf"
  local zones
  zones="$(resolve_geo_zone "$DNS_ZONE")"

  cat > "$out" <<EOF
# Auto-generated by smartdns-geo-conf/scripts/generate-conf.sh
# DNS_ZONE=$DNS_ZONE → zones: $zones
# ZONE_DNS_PROVIDER=$ZONE_DNS_PROVIDER

EOF

  for cc in $zones; do
    printf '# === Zone: %s ===\n\n' "$cc" >> "$out"
    # Generate upstream servers for this zone group
    _generate_zone_servers "$out" "$cc"
    # Generate nameserver routing rules for this zone
    _generate_zone_routing "$out" "$cc"
    printf '\n' >> "$out"
  done

  # Count zones
  local count=0
  for _ in $zones; do
    count=$((count + 1))
  done
  echo "generate-conf: DNS_ZONE=$DNS_ZONE, activated $count zone(s): $zones"
}

# Generate upstream DNS servers for a single zone group.
# Args: $1=output_file $2=cc_code
_generate_zone_servers() {
  local _out="$1" _cc="$2"
  local _group_flags="-group ${_cc} -exclude-default-group"
  local _iface_flag=""

  if [ -n "$ZONE_DNS_INTERFACE" ] && [ "$ZONE_DNS_INTERFACE" != "default" ]; then
    _iface_flag="-interface $ZONE_DNS_INTERFACE"
  fi

  for provider in $ZONE_DNS_PROVIDER; do
    local proto
    proto="$(get_zone_prov "$provider" PROTO)"

    # UDP protocol (ISP Default) — no IP/TLS fields, handle early
    if [ "$proto" = "udp" ]; then
      local _resolv_ips
      _resolv_ips="$(_get_isp_dns_ips)"
      if [ -n "$_resolv_ips" ]; then
        printf '# %s — ISP Default (group %s)\n' "$provider" "$_cc" >> "$_out"
        for _rip in $_resolv_ips; do
          if [ -n "$_iface_flag" ]; then
            printf 'server %s %s %s\n' "$_rip" "$_group_flags" "$_iface_flag" >> "$_out"
          else
            printf 'server %s %s\n' "$_rip" "$_group_flags" >> "$_out"
          fi
        done
        printf '\n' >> "$_out"
      else
        printf '# %s — ISP Default: no ISP DNS found in ndnproxymain.conf\n\n' "$provider" >> "$_out"
      fi
      continue
    fi

    local ip1 ip2 tls_host udp_fb
    ip1="$(get_zone_prov "$provider" IP1)"
    ip2="$(get_zone_prov "$provider" IP2)"
    tls_host="$(get_zone_prov "$provider" TLS_HOST)"
    udp_fb="$(get_zone_prov "$provider" UDP_FALLBACK)" 2>/dev/null || udp_fb="no"

    local _extra=""
    [ -n "$_iface_flag" ] && _extra="$_iface_flag"

    case "$proto" in
      dot)
        printf '# %s DoT (group %s)\n' "$provider" "$_cc" >> "$_out"
        _emit_zone_dot "$_out" "$ip1" "$tls_host" "$_group_flags" "$_extra"
        if [ -n "$ip2" ]; then
          _emit_zone_dot "$_out" "$ip2" "$tls_host" "$_group_flags" "$_extra"
        fi
        ;;
      doh)
        local doh_url
        doh_url="$(get_zone_prov "$provider" DOH_URL)" 2>/dev/null || doh_url=""
        printf '# %s DoH (group %s)\n' "$provider" "$_cc" >> "$_out"
        _emit_zone_doh "$_out" "$doh_url" "$ip1" "$tls_host" "$_group_flags" "$_extra"
        if [ -n "$ip2" ]; then
          _emit_zone_doh "$_out" "$doh_url" "$ip2" "$tls_host" "$_group_flags" "$_extra"
        fi
        ;;
    esac

    # UDP fallback for this provider
    if [ "$udp_fb" = "yes" ]; then
      printf '# %s UDP fallback (group %s)\n' "$provider" "$_cc" >> "$_out"
      printf 'server %s %s\n' "$ip1" "$_group_flags" >> "$_out"
      if [ -n "$ip2" ]; then
        printf 'server %s %s\n' "$ip2" "$_group_flags" >> "$_out"
      fi
      printf '\n' >> "$_out"
    fi
  done
}

# Emit a DoT server with group flags.
# Args: $1=file $2=ip $3=tls_host $4=group_flags $5=extra_flags
_emit_zone_dot() {
  local _file="$1" _ip="$2" _host="$3" _grp="$4" _extra="$5"
  if [ -n "$_extra" ]; then
    cat >> "$_file" <<EOF
server-tls ${_ip}:853 ${_grp} \\
    -host-name ${_host} \\
    -tls-host-verify ${_host} \\
    ${_extra}
EOF
  else
    cat >> "$_file" <<EOF
server-tls ${_ip}:853 ${_grp} \\
    -host-name ${_host} \\
    -tls-host-verify ${_host}
EOF
  fi
}

# Emit a DoH server with group flags.
# Args: $1=file $2=doh_url $3=ip $4=tls_host $5=group_flags $6=extra_flags
_emit_zone_doh() {
  local _file="$1" _url="$2" _ip="$3" _host="$4" _grp="$5" _extra="$6"
  if [ -n "$_extra" ]; then
    cat >> "$_file" <<EOF
server-https ${_url} ${_grp} \\
    -host-name ${_host} \\
    -http-host ${_host} \\
    -host-ip ${_ip} \\
    -tls-host-verify ${_host} \\
    ${_extra}
EOF
  else
    cat >> "$_file" <<EOF
server-https ${_url} ${_grp} \\
    -host-name ${_host} \\
    -http-host ${_host} \\
    -host-ip ${_ip} \\
    -tls-host-verify ${_host}
EOF
  fi
}

# Generate nameserver routing rules for a single zone.
# Args: $1=output_file $2=cc_code
_generate_zone_routing() {
  local _out="$1" _cc="$2"

  printf '# Nameserver routing (%s)\n' "$_cc" >> "$_out"

  # Check if this cc has explicit TLD entries in zone-routing-rules.conf
  local _has_explicit="no"
  if [ -f "$ROUTING_RULES" ]; then
    # Match line starting with "<cc> " (TLD rules, not "+" lines)
    if grep -q "^${_cc}[[:space:]]" "$ROUTING_RULES"; then
      _has_explicit="yes"
    fi
  fi

  if [ "$_has_explicit" = "yes" ]; then
    # Use explicit TLD list from rules file
    local _tlds
    _tlds="$(grep "^${_cc}[[:space:]]" "$ROUTING_RULES" | sed "s/^${_cc}[[:space:]]*//")"
    for tld in $_tlds; do
      printf 'nameserver /%s/%s\n' "$tld" "$_cc" >> "$_out"
    done
  else
    # Implicit rule: only .<cc>
    printf 'nameserver /.%s/%s\n' "$_cc" "$_cc" >> "$_out"
  fi

  # Extra domains (CDN geo-optimization): lines starting with "<cc>+"
  if [ -f "$ROUTING_RULES" ]; then
    local _extras
    _extras="$(grep "^${_cc}+" "$ROUTING_RULES" | sed "s/^${_cc}+[[:space:]]*//" || true)"
    if [ -n "$_extras" ]; then
      for domain in $_extras; do
        printf 'nameserver /%s/%s\n' "$domain" "$_cc" >> "$_out"
      done
    fi
  fi
}

# ===================================================================
# Main
# ===================================================================
main() {
  mkdir -p "$SMARTDNS_CONF_DIR"

  # Generate international DNS servers config
  generate_other_servers
  echo "generate-conf: wrote $CONF_SERVERS_OTHER"
  echo "generate-conf: OTHER_DNS_PROVIDER=$OTHER_DNS_PROVIDER"
  echo "generate-conf: OTHER_DNS_INTERFACES=${OTHER_DNS_INTERFACES:-(direct)}"

  # Generate all-in-one zone config (servers + routing)
  generate_zones_active

  if [ -n "$ZONE_DNS_INTERFACE" ] && [ "$ZONE_DNS_INTERFACE" != "default" ]; then
    echo "generate-conf: ZONE_DNS_INTERFACE=$ZONE_DNS_INTERFACE"
  fi
}

main
