#!/opt/bin/sh
# Configuration for smartdns-conf-ru-split.
# Split-DNS with RU zone routing on Keenetic/Entware.
# shellcheck disable=SC2034  # all variables are used by sourcing scripts
# NOTE: _CONFIG_DIR must be set by the sourcing script before sourcing this file

# SmartDNS daemon init script (stock Entware S38)
S38="/opt/etc/init.d/S38smartdns"

# Active config read by SmartDNS daemon
CONF="/opt/etc/smartdns/smartdns.conf"

# Split-DNS config (RU zone → Yandex/AdGuard, international → Google/CF DoH)
CONF_SPLIT="/opt/etc/smartdns/smartdns-split-dns.conf"

# Default config (simple forwarder, all → Google/CF DoH, no split)
CONF_DEFAULT="/opt/etc/smartdns/smartdns-default.conf"

# State file: exists when split-DNS is enabled.
# Persistent location (survives reboot, not tmpfs).
STATE_FILE="/opt/etc/smartdns/.split-enabled"

# Bind addresses snippet: auto-detected LAN IP bind directives.
# Generated by postinst (same pattern as webui/config/listen.conf).
BIND_ADDRS_CONF="/opt/etc/smartdns/bind-addrs.conf"

# SmartDNS PID file (written by S38/rc.func)
PIDFILE="/opt/var/run/smartdns.pid"

# SmartDNS persistent cache
CACHE_FILE="/opt/var/cache/smartdns.cache"

# SmartDNS listen port (main, used for DNS tests)
SMARTDNS_PORT=6053

# Log tag
LOG_TAG="smartdns-conf-ru-split"
